Refactor to use new router
CPNV-ES/MAW11_Mugiwaras_Looper pull request #18
Opened 2023-11-22 09:14 UTC by Witex15

2023-11-22 09:29 UTC, R0kkxSynetique requested changes

2023-11-22 09:29 UTC, R0kkxSynetique commented on src/controllers/ExercisesController.php
The method previously called index has no sense when renamed manage.
Setting the title as empty might need to have a validation instead.
Most of the methods aren't contextually correctly named.

2023-11-22 09:29 UTC, LeZderich approved these changes
I approve the PR.
In the future we'll need to rename the methods on the controllers.

2023-11-24 07:38 UTC, Witex15 commented on src/controllers/ExercisesController.php
corrected

2023-11-24 07:40 UTC, R0kkxSynetique approved these changes

2023-11-24 07:40 UTC, merged